export const FILTER_PRESETS = [
  { id: 'original', label: 'Original', adj: {}, css: 'none' },
  { id: 'grayscale', label: 'Grayscale', adj: { grayscale: 100 }, css: 'grayscale(1)' },
  { id: 'sepia', label: 'Sepia', adj: { sepia: 100, temperature: 18 }, css: 'sepia(0.85)' },
  {
    id: 'vintage',
    label: 'Vintage',
    adj: { saturation: -18, contrast: 12, sepia: 42, temperature: 22 },
    matrix: 'Vintage',
    css: 'sepia(0.45) contrast(1.1) saturate(0.85)',
  },
  { id: 'warm', label: 'Warm', adj: { temperature: 42, saturation: 12 }, css: 'sepia(0.25) saturate(1.2)' },
  { id: 'cool', label: 'Cool', adj: { temperature: -38, tint: -8 }, css: 'hue-rotate(190deg) saturate(1.05)' },
  {
    id: 'cinematic',
    label: 'Cinematic',
    adj: { contrast: 22, saturation: -12, shadows: 18, highlights: -14, temperature: 8 },
    css: 'contrast(1.2) saturate(0.9) brightness(0.96)',
  },
  {
    id: 'dramatic',
    label: 'Dramatic',
    adj: { contrast: 38, shadows: 28, highlights: -18, saturation: 8 },
    css: 'contrast(1.35) brightness(0.92)',
  },
  { id: 'bright', label: 'Bright', adj: { brightness: 22, exposure: 14, highlights: 8 }, css: 'brightness(1.2)' },
  { id: 'highContrast', label: 'High Contrast', adj: { contrast: 44 }, css: 'contrast(1.45)' },
  { id: 'fade', label: 'Fade', adj: { contrast: -18, saturation: -16, brightness: 10 }, css: 'contrast(0.85) saturate(0.8) brightness(1.08)' },
  { id: 'noir', label: 'Noir', adj: { grayscale: 100, contrast: 32, shadows: 18 }, css: 'grayscale(1) contrast(1.3)' },
  {
    id: 'retro',
    label: 'Retro',
    adj: { sepia: 48, contrast: 14, temperature: 28, saturation: 16 },
    matrix: 'Kodachrome',
    css: 'sepia(0.4) contrast(1.15) saturate(1.2)',
  },
  { id: 'vivid', label: 'Vivid', adj: { saturation: 38, vibrance: 28, contrast: 10 }, css: 'saturate(1.5) contrast(1.1)' },
  { id: 'soft', label: 'Soft', adj: { blur: 10, brightness: 8, contrast: -8, highlights: 10 }, css: 'brightness(1.08) contrast(0.92) blur(0.4px)' },
  {
    id: 'duotone',
    label: 'Duotone',
    adj: { grayscale: 70, contrast: 16 },
    blend: { color: '#0ea5e9', mode: 'overlay', alpha: 0.42 },
    css: 'grayscale(0.8) contrast(1.15) sepia(0.2) hue-rotate(170deg)',
  },
];
